#!/bin/sh
while xsetroot -name "`date`"; do
  sleep 1
done &
wmname LG3D &
xautolock -time 10 -locker i3lock -detectsleep &
dropbox start &
_JAVA_AWT_WM_NONREPARENTING=1 exec ssh-agent ${HOME}/bin/dwm
